# Thai-lint Configuration
# AI-focused code quality linting
# https://github.com/be-wise-be-kind/thai-lint

# DRY - Duplicate code detection
min_duplicate_lines: 5

# Nesting - Maximum nesting depth for control structures
max_nesting_depth: 4

# Magic numbers - Only these numeric literals are allowed without naming
allowed_numbers:
  - 0
  - 1
  - -1
  - 100

# SRP - Single Responsibility Principle
# Maximum number of public methods per class
max_public_methods: 10

# File size limits
max_file_lines: 500

# Documentation hygiene
# file-header: Require documentation headers in key files
require_file_headers: true
file_header_paths:
  - "src/lib/**/*.ts"
  - "src/db/**/*.ts"
  - "src/mcp/**/*.ts"

# lazy-ignores: Flag unjustified lint suppressions
disallow_lazy_ignores: true

# print-statements: No console.log in production
disallow_print_statements: true
print_statement_exceptions:
  - "src/lib/logger.ts"

# Paths to include
include:
  - "src/**/*.ts"
  - "src/**/*.tsx"

# Paths to exclude
exclude:
  - "node_modules/**"
  - ".next/**"
  - "drizzle/**"
  - "**/*.d.ts"
  - "**/*.config.ts"
